package com.purduediet.helloworld.purduedietdining.objects;
import java.util.*;

public class DiningCourt {
    private List<ItemFood> foods;

    public DiningCourt(){
        foods = new ArrayList<ItemFood>();
        foods.add(new ItemFood("Ford", "Lunch","BoilerQ","Beef Barbacoa",115,9,false,true));
        foods.add(new ItemFood("Ford", "Lunch","BoilerQ","Chicken Fajitas",262,26,false,false));
        foods.add(new ItemFood("Ford", "Lunch","BoilerQ","Flour Tortilla",134,4,true,false));
        foods.add(new ItemFood("Ford", "Lunch","BoilerQ","Taco Shells",51,1,true,true));
        foods.add(new ItemFood("Ford", "Lunch","BoilerQ","Tortilla Chips",134,2,true,true));
        foods.add(new ItemFood("Ford", "Lunch","Potāto, Potäto","Scrambled Eggs",127,9,true,true));
        foods.add(new ItemFood("Ford", "Lunch","Potāto, Potäto","Apple French Toast Stuffed Casserole",221,8,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Potāto, Potäto","Quiche Lorraine",335,13,false,false));
        foods.add(new ItemFood("Ford", "Lunch","Potāto, Potäto","Hash Brown Breakfast Casserole",153,4,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Potāto, Potäto","Sausage Links",166,6,false,true));
        foods.add(new ItemFood("Ford", "Lunch","International Market","Tempura Orange Pork",349,16,false,false));
        foods.add(new ItemFood("Ford", "Lunch","International Market","Whole Green Beans",40,2,true,true));
        foods.add(new ItemFood("Ford", "Lunch","International Market","Mini Spring Rolls",35,1,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Parmesan Tomato","Cherry Dessert Pizza",280,4,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Parmesan Tomato","Pepperoni Pizza",188,10,false,false));
        foods.add(new ItemFood("Ford", "Lunch","Parmesan Tomato","Garlic Cheese Pizza",200,8,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Salami and Swiss","Mexican Wrap",431,12,false,false));
        foods.add(new ItemFood("Ford", "Lunch","Salami and Swiss","Seasoned Kettle Chips",162,2,true,true));
        foods.add(new ItemFood("Ford", "Lunch","Salami and Swiss","Creamy Macaroni Salad",1032,16,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Salami and Swiss","Deli & Fresh Baked Breads",220,5,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Sugar Hill","Assorted Donuts",195,2,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Sugar Hill","Chocolate Chip Bar",215,3,true,false));
        foods.add(new ItemFood("Ford", "Lunch","Sugar Hill","Iced Coffee",124,3,true,true));
        foods.add(new ItemFood("Ford", "Dinner","BoilerQ","Barbecue Pork Loin",338,27,false,true));
        foods.add(new ItemFood("Ford", "Dinner","BoilerQ","Spicy Breaded Chicken Breast",243,15,false,true));
        foods.add(new ItemFood("Ford", "Dinner","BoilerQ","Smashed Red Potatoes",229,4,true,false));
        foods.add(new ItemFood("Ford", "Dinner","BoilerQ","Buttermilk Cornbread",126,3,true,false));
        foods.add(new ItemFood("Ford", "Dinner","BoilerQ","Grilled Pineapple Wedge",41,0,true,true));
        foods.add(new ItemFood("Ford", "Dinner","International Market","Cashew Chicken",155,10,false,true));
        foods.add(new ItemFood("Ford", "Dinner","International Market","Sugar Snap Pea Stir Fry",89,3,true,true));
        foods.add(new ItemFood("Ford", "Dinner","International Market","Brown Rice",125,3,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Salami and Swiss","Buffalo Chicken Sandwich",551,42,false,false));
        foods.add(new ItemFood("Ford", "Dinner","Salami and Swiss","Creamy Macaroni Salad",1032,16,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Potāto, Potäto","Cincinnati Skyline Chili",371,24,false,true));
        foods.add(new ItemFood("Ford", "Dinner","Potāto, Potäto","Meatless Chili",172,7,true,true));
        foods.add(new ItemFood("Ford", "Dinner","Potāto, Potäto","Garlic Bread",170,3,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Potāto, Potäto","Oyster Cracker",119,3,false,true));
        foods.add(new ItemFood("Ford", "Dinner","Potāto, Potäto","Kidney Beans",127,8,true,true));
        foods.add(new ItemFood("Ford", "Dinner","Parmesan Tomato","Tomato Bacon Pesto Pizza",202,10,false,false));
        foods.add(new ItemFood("Ford", "Dinner","Parmesan Tomato","Sausage Pizza",222,12,false,false));
        foods.add(new ItemFood("Ford", "Dinner","Parmesan Tomato","Garlic Cheese Pizza",200,8,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Sugar Hill","Chocolate Chip Cookie",185,2,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Sugar Hill","Sugar Cookie",179,2,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Sugar Hill","M & M Brownie",195,2,true,false));
        foods.add(new ItemFood("Ford", "Dinner","Sugar Hill","Apple Hi Pie",401,3,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","Granite Grill","Turkey Burger",227,20,false,false));
        foods.add(new ItemFood("Earhart", "Lunch","Granite Grill","Steak Fries",118,2,false,false));
        foods.add(new ItemFood("Earhart", "Lunch","Granite Grill","Hamburgers",354,17,false,false));
        foods.add(new ItemFood("Earhart", "Lunch","Souper Deli","Tuscan Soup",99,7,false,true));
        foods.add(new ItemFood("Earhart", "Lunch","Souper Deli","Deli w/Fresh Baked Breads",220,5,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","Totally Italian","Make Your Own Pizza",0,0,false,false));
        foods.add(new ItemFood("Earhart", "Lunch","No Wheat No Meat","Roasted Eggplant and Vegetables",93,2,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","No Wheat No Meat","Corn",74,2,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Oven Crisp Chicken Breast",383,36,false,true));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Scrambled Eggs",127,9,false,true));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Roasted Cajun Fingerling Potatoes",248,5,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Sausage Links",166,6,false,false));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Green Bean Casserole",70,2,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","Heartland Classics","Corn",74,2,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","The Gallery","Honey Sesame Chicken",235,21,false,true));
        foods.add(new ItemFood("Earhart", "Lunch","The Gallery","Broccoli Carrot Stir Fry",55,3,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","The Gallery","Make Your Own Stir Fry",0,0,true,true));
        foods.add(new ItemFood("Earhart", "Lunch","The Pastry Shop","Boston Cream Pie",303,4,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","The Pastry Shop","White Chocolate Macadamia Cookie",174,2,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","The Pastry Shop","Snickerdoodle Cookie",184,2,true,false));
        foods.add(new ItemFood("Earhart", "Lunch","The Pastry Shop","Lemon Cream Cake",384,5,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","Granite Grill","Turkey Burger",227,20,false,false));
        foods.add(new ItemFood("Earhart", "Dinner","Granite Grill","Steak Fries",118,2,false,false));
        foods.add(new ItemFood("Earhart", "Dinner","Granite Grill","Hamburgers",354,17,false,false));
        foods.add(new ItemFood("Earhart", "Dinner","Souper Deli","Tuscan Soup",99,7,false,true));
        foods.add(new ItemFood("Earhart", "Dinner","Souper Deli","Deli w/Fresh Baked Breads",220,5,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","Totally Italian","Make Your Own Pizza",0,0,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","No Wheat No Meat","Roasted Eggplant and Vegetables",93,2,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","No Wheat No Meat","Whole Green Beans",40,2,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Mesquite Seasoned Bone In Chicken Breast",431,42,false,true));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Vegetarian Taco Pizza",219,8,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Shrimp Scampi Pasta",334,14,false,false));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Italian Style Greeen Beans",108,2,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Garlic Mashed Potatoes",74,2,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","Heartland Classics","Fordhook Lima Beans",155,9,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","The Gallery","Honey Sesame Chicken",235,21,false,true));
        foods.add(new ItemFood("Earhart", "Dinner","The Gallery","Vegan Broccoli Mushroom Stir Fry",88,2,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","The Gallery","Make Your Own Stir Fry",0,0,true,true));
        foods.add(new ItemFood("Earhart", "Dinner","The Pastry Shop","Oreo Brownie",264,2,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","The Pastry Shop","White Chocolate Macadamia Cookie",174,2,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","The Pastry Shop","Snickerdoodle Cookie",184,2,true,false));
        foods.add(new ItemFood("Earhart", "Dinner","The Pastry Shop","Lemon Cream Cake",384,5,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Romeo and Parmesan","Omelet or Breakfast Skillet",0,0,false,true));
        foods.add(new ItemFood("Wiley", "Breakfast","Mozzarella Fresca","Assorted Donuts",195,2,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Mozzarella Fresca","Apple Coffeecake",278,3,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Scrambled Eggs",127,9,false,true));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Homestyle Sausage Gravy",226,22,false,true));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Biscuits",192,4,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Smokey Links",166,6,false,true));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Mary's Hash Browns",96,6,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Farina",68,1,true,false));
        foods.add(new ItemFood("Wiley", "Breakfast","Classic Flavors","Texas French Toast",275,9,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Open Flame","Hamburger",250,15,false,false));
        foods.add(new ItemFood("Wiley", "Lunch","Open Flame","Potato Gems",197,2,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Open Flame","Smoked St. Louis BBQ Ribs",238,13,false,true));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Sarjent Zupo's Pizza Casserole",337,14,false,false));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Eggplant Parmesan",238,10,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Sour Cream & Chive Mashed Potatoes",177,3,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Roasted Tuscan Spaghetti Squash",75,3,false,false));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Marinara Sauce",61,2,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Vegan Roasted Seasoned Broccoli",112,3,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Classic Flavors","Corn Dogs",189,6,false,false));
        foods.add(new ItemFood("Wiley", "Lunch","Mozzarella Fresca","Crispy Cheese Pizza",138,5,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Mozzarella Fresca","Crispy Chicken Cordon Bleu Pizza",172,10,false,false));
        foods.add(new ItemFood("Wiley", "Lunch","No Wheat No Meat","Greek Artichoke and Bean Stew",208,10,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","No Wheat No Meat","Green Beans",16,1,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Romeo and Parmesan","Garlic Breadstick",163,4,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Romeo and Parmesan","Made to Order Venetian Pasta Bar",463,3,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Churrascaria","Antipasto Bar",0,0,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Churrascaria","Roasted Turkey Breast",61,12,false,true));
        foods.add(new ItemFood("Wiley", "Lunch","Churrascaria","Chicken Drumsticks Garlic Butter Wiley",310,23,false,true));
        foods.add(new ItemFood("Wiley", "Lunch","Churrascaria","Wild Rice",97,3,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Churrascaria","Cranberry Waldorf Nut Salad",165,1,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Genoa Salami",110,6,false,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Sliced Cojack Cheese",81,5,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Spinach Beet Salad",114,2,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Fresh Tastes Salads",100,2,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Tropical Fruit Salad",99,0,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Fresh Tastes","Blueberries",40,0,true,true));
        foods.add(new ItemFood("Wiley", "Lunch","Delectables","Dalmation Cookie",242,3,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Delectables","Strawberry Shortcake Cookie",169,1,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Delectables","Strawberry Rhubarb Pie",368,3,true,false));
        foods.add(new ItemFood("Wiley", "Lunch","Delectables","Danish Cherry Streusel",220,3,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Open Flame","Chicken Breast Home Fry Seasoning Wiley",226,34,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Open Flame","Potato Gems",197,2,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Open Flame","Smoked St. Louis BBQ Ribs",238,13,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","Thai Sweet N Hot Turkey Meatballs",148,10,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","White Mini Sub Bun",148,6,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","Kashmir Chicken",160,20,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","Roasted Tuscan Spaghetti Squash",75,3,false,false));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","California Vegetables",18,1,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","Steamed Chinese Bao",70,3,false,false));
        foods.add(new ItemFood("Wiley", "Dinner","Classic Flavors","Converted Rice",75,1,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Mozzarella Fresca","Crispy Cheese Pizza",138,5,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Mozzarella Fresca","Crispy Chicken Cordon Bleu Pizza",172,10,false,false));
        foods.add(new ItemFood("Wiley", "Dinner","No Wheat No Meat","Greek Artichoke and Bean Stew",208,10,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","No Wheat No Meat","Converted Rice",75,1,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","No Wheat No Meat","Green Beans",16,1,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Romeo and Parmesan","Made to Order Venetian Pasta Bar",463,3,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Romeo and Parmesan","Sundried Tomato Garlic Focaccia",65,1,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Churrascaria","Antipasto Bar",0,0,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Churrascaria","Roasted Turkey Breast",61,12,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Churrascaria","Chicken Drumsticks Garlic Butter Wiley",310,23,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Churrascaria","Wild Rice",97,3,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Churrascaria","Cranberry Waldorf Nut Salad",165,1,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Genoa Salami",110,6,false,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Sliced Cojack Cheese",81,5,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Spinach Beet Salad",114,2,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Fresh Tastes Salads",100,1,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Tropical Fruit Salad",99,0,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Fresh Tastes","Blueberries",40,0,true,true));
        foods.add(new ItemFood("Wiley", "Dinner","Delectables","Dalmation Cookie",242,3,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Delectables","Strawberry Shortcake Cookie",169,1,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Delectables","Angel Food Cake",368,3,true,false));
        foods.add(new ItemFood("Wiley", "Dinner","Delectables","Strawberry Rhubarb Pie",220,3,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Vegetarian Chik Nugget",47,3,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Hidden Valley Ranch Dressing",54,0,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Honey Mustard Dressing",52,0,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Macaroni & Cheese",346,15,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Baked Beans",189,6,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Portobello Road - Vegetarian","Peas",53,4,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","Abby Road Deli","Deli & Fresh Baked Breads",220,5,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Devonshire Way","Monster Cookie (contains Peanut Butter)",342,6,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Devonshire Way","White Cupcake",189,2,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Devonshire Way","Mint Brownie",254,2,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Devonshire Way","Shortbread Cookie",244,2,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Regent Grill","Nachos Grande",411,17,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Regent Grill","Chicken Tacos",108,11,false,false));
        foods.add(new ItemFood("Windsor", "Dinner","Regent Grill","Corn",74,2,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","SoHo International Market","Carved Ham",184,21,false,false));
        foods.add(new ItemFood("Windsor", "Dinner","SoHo International Market","Whipped Sweet Potatoes",247,3,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","SoHo International Market","Sweet Yeasty Rolls",186,4,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","SoHo International Market","Green Beans",16,1,true,true));
        foods.add(new ItemFood("Windsor", "Dinner","Burrito Bar","Chicken Carnita",94,9,false,false));
        foods.add(new ItemFood("Windsor", "Dinner","Burrito Bar","Vegan Sofritas",87,7,true,false));
        foods.add(new ItemFood("Windsor", "Dinner","Burrito Bar","Burritos Your Way",450,14,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Creation Station","Build Your Own Biscuit Bowl",375,7,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Creation Station","Boneless Wings (5 pieces)",88,5,false,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Top Your Own Oatmeal (1 cup)",150,6,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Mr. Pibb Chicken Drumstick",265,18,false,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Greek Tilapia Mozzarella",222,30,false,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Pepperjack Cheese Quiche",380,15,false,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Turkey Sloppy Joe",158,15,false,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Sunshine Vegetables",45,2,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Broccoli Spears",12,1,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Heartland Classics","Fresh Redskin Whipped Potatoes",146,2,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Stack it up Deli","Whipped Cream Cheese",46,1,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Stack it up Deli","White Whole Grain Bagel",179,7,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Stack it up Deli","Dip It Bar",0,0,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Stack it up Deli","Deli Subs",0,0,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Leaf n Ladle","Yogurt Bar",262,3,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Leaf n Ladle","Mandarin Green Salad",228,1,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","3rd Street Grill","Build Your Own Biscuit Bowl",375,7,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Chef Choice","Honey Mustard Dressing",52,0,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Chef Choice","Rub Asian Dry",31,0,true,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Chef Choice","Boneless Wings",88,5,false,true));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Daily Feature","Pork Burger",224,14,false,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Daily Feature","Steak Fries",118,2,false,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Temptations","Black and Gold Cookie",242,3,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Temptations","Pumpkin Sugar Cookie",340,2,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Temptations","Assorted Donuts",195,2,true,false));
        foods.add(new ItemFood("Hillenbrand", "Lunch","Temptations","Grasshopper Pie",75,4,true,false));

    }


}
